model:
  name: MoreFcModel
  input_channels: 6
  depth: 1

lr: 1e-3
device: 'mps'
batch_size: 128
balance_samples: True
train_x_files: ['dataset/gesture_merged/train_x.npy']
train_y_files: ['dataset/gesture_merged/train_y.npy']
valid_x_files: ['dataset/gesture_merged/test_x.npy']
valid_y_files: ['dataset/gesture_merged/test_y.npy']
labels: [ none, wave_right, wave_down, wave_left, wave_up, tap_air, tap_plane, push_forward,
        pinch, clench, flip, wrist_clockwise, wrist_counterclockwise, circle_clockwise,
        circle_counterclockwise, clap, snap, thumb_up, middle_pinch, index_flick, touch_plane,
        thumb_tap_index, index_bend_and_straighten, ring_pinch, pinky_pinch, slide_plane,
        pinch_down, pinch_up, boom, tap_up, throw, touch_left, touch_right, slide_up,
        slide_down, slide_left, slide_right, aid_slide_left, aid_slide_right, touch_up,
        touch_down, touch_ring, long_touch_ring, spread_ring]
use_labels: [ none, wave_right, wave_down, wave_left, wave_up, tap_air, tap_plane, push_forward,
        pinch, clench, flip, wrist_clockwise, wrist_counterclockwise, circle_clockwise,
        circle_counterclockwise, clap, snap, thumb_up, middle_pinch, index_flick, touch_plane,
        thumb_tap_index, index_bend_and_straighten, ring_pinch, pinky_pinch, slide_plane,
        pinch_down, pinch_up, boom, tap_up, throw, touch_left, touch_right, slide_up,
        slide_down, slide_left, slide_right, aid_slide_left, aid_slide_right, touch_up,
        touch_down, touch_ring, long_touch_ring, spread_ring]